//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SendAlerts.Resources;

using System;
using System.Resources;

/// <summary>
/// A strongly-typed resource class for accessing localized strings.
/// </summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceManager == null)
            {
                _resourceManager = new ResourceManager("SendAlerts.Resources.Strings", typeof(Strings).Assembly);
            }
            return _resourceManager;
        }
    }
}
